export const jsonMapping = {
    "n5": require('../_database/frases/frases_n5.json'),
    "adverbios": require('../_database/frases/frases_n5_adverbos_frequencia.json'),
    "adjetivos": require('../_database/frases/frases_n5_adjetivos.json'),
    "animais": require('../_database/frases/frases_n5_vocabulario_animais.json'),
    "contagem": require('../_database/frases/frases_n5_vocabulario_contagem.json'),
    "escola": require('../_database/frases/frases_n5_vocabulario_escolar.json'),
    "familia": require('../_database/frases/frases_n5_vocabulario_familia.json'),
    "hospital": require('../_database/frases/frases_n5_vocabulario_hospital.json'),
    "profissoes": require('../_database/frases/frases_n5_vocabulario_profissoes.json'),
    "restaurante": require('../_database/frases/frases_n5_vocabulario_restaurante.json'),
    "kissintokyo": require('../_database/frases/kissintokyo.json'),
    "forma ta": require('../_database/frases/frases_forma_ta.json'),
    "forma te": require('../_database/frases/frases_forma_te.json'),
    "forma ukemi": require('../_database/frases/frases_forma-ukemi.json'),
    "forma tai": require('../_database/frases/frases_forma_tai.json'),
    "forma shieki": require('../_database/frases/frases_forma_shieki.json'),
    "forma shieki ukemi": require('../_database/frases/frases_forma_shieki-ukemi.json'),
    "forma nai": require('../_database/frases/frases_forma_nai.json'),
    "forma masen": require('../_database/frases/frases_forma_masen.json'),
    "forma kanou": require('../_database/frases/frases_forma_kanou.json'),
    "forma ikou": require('../_database/frases/frases_forma_ikou.json'),
    "forma ba": require('../_database/frases/frases_forma_ba.json'),
};